### ISSUE TITLE
Single line comment causes parsing exception

### ISSUE THREAD

**Issue by edeca** [plyara/plyara#63] opened 2019-10-03 15:13 UTC
A file containing only a single line comment, such as:

    // This rule file has been deleted

Causes the exception: 

    plyara.exceptions.ParseTypeError: Unknown text / for token of type FORWARDSLASH on line 1

Although this is an edge case, the rule is parsed correctly by Yara itself (and the Python module).  It would be good to understand if this is a bug, or if I should continue to work around it with exception handling.

**Comment by Taskr** [comment] 2019-10-03 16:12
Will take a look later today. This should be able to be fixed by adding comment token to be part of ruleset parsing.

**Comment by utkonos** [comment] 2020-01-05 03:50
I am unable to reproduce this bug. However, I have added a unit test for the type of file that is just a single line and a comment. If this bug returns it will be noticed by CI.

Thanks for the report.

**Closed by utkonos** 2020-01-05 03:50 UTC
Labels: bug, invalid
