### ISSUE TITLE
Yet another problem with minuses/dashes parsing in condition terms

### ISSUE THREAD

**Issue by rakovskij-stanislav** [plyara/plyara#115] opened 2021-03-09 11:45 UTC
```yara
rule bad_parsed_subtraction{
    meta:
        author = "Rakovskij Stanislav / disasm.me"
        date = "09.03.2021"
        description = "test rule in which we have bad parsing of minus sign between two variables"
    strings:
        $a = "Test"
        $b = "Test 2"
    condition:
         @a-@b<128
}


rule good_parsed_addiction{
    meta:
        author = "Rakovskij Stanislav / disasm.me"
        date = "09.03.2021"
        description = "test rule in which we have bad parsing of minus sign between two variables"
    strings:
        $a = "Test"
        $b = "Test 2"
    condition:
         @a+@b<128
}
```

```python
>>> parser = plyara.Plyara(); rules = parser.parse_string(open("bad_parse.yar").read())
>>> rules[0]["condition_terms"]
['@a-', '@b', '<', '128']
>>> rules[1]["condition_terms"]
['@a', '+', '@b', '<', '128']
```

**Comment by rakovskij-stanislav** [comment] 2021-03-09 11:53
And totally "wow" case with extra empty line!

```yara
rule rule_extra_empty_line
{
    meta:
        author = "Rakovskij Stanislav / disasm.me"
        date = "09.03.2021"
        description = "actually magic"
    strings:
        $a = "hello"
        $b = "world"
    condition:
        @b-@a<128
}
```

```
>>> rules[0]["condition_terms"]
['@b', '-', '', '@a', '<', '128']
```

**Comment by utkonos** [comment] 2021-03-29 12:20
Thanks for the report. Will get this fixed.

**Comment by utkonos** [comment] 2024-12-08 23:47
The root cause of this is the same as https://github.com/plyara/plyara/issues/112
This can be closed as a duplicate.

**Comment by utkonos** [comment] 2024-12-08 23:48
The root cause of this is the same as https://github.com/plyara/plyara/issues/112
This can be closed as a duplicate.

**Closed by utkonos** 2024-12-08 23:48 UTC
Labels: bug, duplicate
