### ISSUE TITLE
Metadata structure in 2.0.0

### ISSUE THREAD

**Issue by Neo23x0** [plyara/plyara#52] opened 2019-02-23 13:18 UTC
Is there a reason why you've decided to change the metadata structure from `dict` to a `list of dicts`?

Before:
```
        "metadata": {
            "MyBool": "true", 
            "MyInt": "10", 
            "MyString": "Test"
        },
``` 
Now:
```
        "metadata": [
            {
                "MyString": "Test"
            },
            {
                "MyInt": 10
            },
            {
                "MyBool": true
            }
        ],
```

Why not?
```
        "metadata": {
            "MyBool": true, 
            "MyInt": 10, 
            "MyString": "Test"
        },
``` 

For me it makes it more difficult to handle metadata values. I cannot do things like that anymore:
```
if 'date' in rule['metadata']:
   ...
```

**Comment by utkonos** [comment] 2019-02-23 18:38
@Neo23x0 Yes, we have a few reasons for that design decision. First, meta can have multiple identical key names. This does not generate an error in YARA. We were able to support this in the old format, but it made the rule rebuilding code difficult. To facilitate rule rebuilding, the meta section uses the same format as the strings did before.

We have had other users ask for the old format, so I'm working on a quick patch to add a flag so the two formats can coexist.

**Comment by utkonos** [comment] 2019-02-23 19:37
Duplicate of #49

**Comment by utkonos** [comment] 2019-02-23 19:50
@Neo23x0 Patch is almost ready. Please respond over in #49

**Closed** 2020-07-17 03:36 UTC
Labels: duplicate
